TRAIN:
  DEVICE: "cpu"
  GPU_ID: "0"
  NUM_EPOCHS: 15
  LEARNING_RATE: 0.00001
  BATCH_SIZE: 32
  MODEL_NAME: "small_bert/bert_en_uncased_L-4_H-512_A-8"
DATASET:
  LABELS: "./../../data/labels.txt"
  TRAIN_PATH: "./../../data/texts/strain/"
  TEST_PATH: "./../../data/texts/stest/"